# Generated by Django 5.2 on 2025-04-29 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_ingredient', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('recommended_drink', models.CharField(max_length=100)),
                ('alt_ingredient', models.IntegerField()),
                ('is_bought', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('shopping_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ingredients_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None)),
            ],
        ),
    ]
