# Generated by Django 5.2 on 2025-04-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
