# Generated by Django 5.2 on 2025-04-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0002_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='Shopping_List',
        ),
    ]
