# Generated by Django 5.2 on 2025-04-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0003_rename_shoppinglist_shopping_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_List',
            new_name='ShoppingList',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_ID',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='shopping_ID',
            new_name='shopping_id',
        ),
    ]
