# Generated by Django 5.2 on 2025-05-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0005_recipe_recipeingredient_recipe_ingredients_user_and_more'),
    ]

    operations = [
    ]
