# Generated by Django 5.2 on 2025-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0005_recipe_recipeingredient_recipe_ingredients_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shopping_id',
            new_name='shopping_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
