# Generated by Django 5.2 on 2025-05-05 15:34

from django.db import migrations, models  # Import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0006_auto_20250505_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tm_api.User',
            ),
        ),
    ]