# Generated by Django 5.2 on 2025-05-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0007_auto_20250505_1534'),
        ('tm_api', '0007_ingredient_user_shoppinglist_owner_and_more'),
    ]

    operations = [
    ]
